---
output:
  github_document:
    html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Statistics and Quantitative Methods (Semester 1)

<!-- badges: start -->
<!-- badges: end -->

Welcome to the main site of the course *Statistics and Quantitative Methods* (Semester 1).

This will be your go-to place throughout the semester.
Use the menu above to navigate to info pages under `Course info`.

This course is an introduction to study design, statistics and quantitative data analysis as commonly employed in linguistics, using the R software.


## Course description

The course will cover the basics of statistics and quantitative data analysis, and how to design studies that effectively address the intended research questions. Students will learn the principles of data visualisation and statistical modelling and develop the practical skills necessary to perform such analyses. The course will draw examples from different branches of linguistics and will provide students with hands-on experience in open science practices.

The course will teach you how to carry out statistical inference using Null Hypothesis Significance Testing and how to correctly interpret p-values and confidence intervals.

